// Code generated by go-swagger; DO NOT EDIT.

package hello_tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// IDOfHelloEndpointHandlerFunc turns a function with the right signature into a id of hello endpoint handler
type IDOfHelloEndpointHandlerFunc func(IDOfHelloEndpointParams) middleware.Responder

// Handle executing the request and returning a response
func (fn IDOfHelloEndpointHandlerFunc) Handle(params IDOfHelloEndpointParams) middleware.Responder {
	return fn(params)
}

// IDOfHelloEndpointHandler interface for that can handle valid id of hello endpoint params
type IDOfHelloEndpointHandler interface {
	Handle(IDOfHelloEndpointParams) middleware.Responder
}

// NewIDOfHelloEndpoint creates a new http.Handler for the id of hello endpoint operation
func NewIDOfHelloEndpoint(ctx *middleware.Context, handler IDOfHelloEndpointHandler) *IDOfHelloEndpoint {
	return &IDOfHelloEndpoint{Context: ctx, Handler: handler}
}

/*IDOfHelloEndpoint swagger:route POST /hello hello-tag idOfHelloEndpoint

Hello returns hello world string with given input.

*/
type IDOfHelloEndpoint struct {
	Context *middleware.Context
	Handler IDOfHelloEndpointHandler
}

func (o *IDOfHelloEndpoint) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewIDOfHelloEndpointParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
