// Code generated by go-swagger; DO NOT EDIT.

package hello_tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"swaggerbug/models"
)

// IDOfHelloEndpointOKCode is the HTTP code returned for type IDOfHelloEndpointOK
const IDOfHelloEndpointOKCode int = 200

/*IDOfHelloEndpointOK This text will appear as description of your response body.

swagger:response idOfHelloEndpointOK
*/
type IDOfHelloEndpointOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Hello `json:"body,omitempty"`
}

// NewIDOfHelloEndpointOK creates IDOfHelloEndpointOK with default headers values
func NewIDOfHelloEndpointOK() *IDOfHelloEndpointOK {

	return &IDOfHelloEndpointOK{}
}

// WithPayload adds the payload to the id of hello endpoint o k response
func (o *IDOfHelloEndpointOK) WithPayload(payload []*models.Hello) *IDOfHelloEndpointOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the id of hello endpoint o k response
func (o *IDOfHelloEndpointOK) SetPayload(payload []*models.Hello) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IDOfHelloEndpointOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Hello, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
