// Code generated by go-swagger; DO NOT EDIT.

// Package restapi hello.
//
//  Documentation of our hello API.
//  Schemes:
//    http
//  Host: localhost:8080
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
