// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Documentation of our hello API.",
    "title": "hello.",
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "paths": {
    "/hello": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "hello-tag"
        ],
        "summary": "Hello returns hello world string with given input.",
        "operationId": "idOfHelloEndpoint",
        "parameters": [
          {
            "type": "string",
            "x-go-name": "Name",
            "name": "name",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/helloResponse"
          }
        }
      }
    }
  },
  "definitions": {
    "Hello": {
      "type": "object",
      "properties": {
        "message": {
          "$ref": "#/definitions/Message"
        }
      },
      "x-go-package": "github.com/glindsell/hello/api"
    },
    "Message": {
      "type": "object",
      "properties": {
        "words": {
          "type": "string",
          "x-go-name": "Body"
        }
      },
      "x-go-package": "github.com/glindsell/hello/api"
    }
  },
  "responses": {
    "helloResponse": {
      "description": "This text will appear as description of your response body.",
      "schema": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/Hello"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Documentation of our hello API.",
    "title": "hello.",
    "version": "1.0.0"
  },
  "host": "localhost:8080",
  "basePath": "/",
  "paths": {
    "/hello": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "hello-tag"
        ],
        "summary": "Hello returns hello world string with given input.",
        "operationId": "idOfHelloEndpoint",
        "parameters": [
          {
            "type": "string",
            "x-go-name": "Name",
            "name": "name",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "This text will appear as description of your response body.",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Hello"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Hello": {
      "type": "object",
      "properties": {
        "message": {
          "$ref": "#/definitions/Message"
        }
      },
      "x-go-package": "github.com/glindsell/hello/api"
    },
    "Message": {
      "type": "object",
      "properties": {
        "words": {
          "type": "string",
          "x-go-name": "Body"
        }
      },
      "x-go-package": "github.com/glindsell/hello/api"
    }
  },
  "responses": {
    "helloResponse": {
      "description": "This text will appear as description of your response body.",
      "schema": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/Hello"
        }
      }
    }
  }
}`))
}
